### ISSUE TITLE
Do not reinvent the wheel, call .NET code from Python

### ISSUE THREAD

**Issue by 0x8DEADF00D** [Der-Eddy/pyepvp#1]
Recoding every function is not necessary and thus wasted time. How about just wrapping the original library? 

You may take a look at [this question on stackoverflow](http://stackoverflow.com/questions/7367976/calling-a-c-sharp-library-from-python).

**Comment by Der-Eddy** [comment]
In that case I could also just use the .NET Library. But I make this for fun because I needed an interesting python project :p
